project_id = "bedrtkwvfkgrjerqllkg"

[functions.get-weather-forecast]
verify_jwt = false

[functions.seed-database]
verify_jwt = false

[functions.ai-crop-recommendation]
verify_jwt = false

[functions.ai-disease-forecast]
verify_jwt = false

[functions.ai-generate-tasks]
verify_jwt = false